name: Enketo Blog
exclude: [ README.md, build.sh, Gemfile, Gemfile.lock, npm-debug.log, package.json ]
port: 4000
permalink: /:title
analytics: UA-6765789-12
comments: true
safe: true
url: https://blog.enketo.org
